### ISSUE TITLE
博客目前存在的一些问题

### ISSUE THREAD

**Issue by seisman** [marscfeng/marscfeng.github.io#1]
恭喜开博～说几个我看到的博客的问题：
1. 部分内容的显示不对，应该是markdown文件语法没写对导致的，比如
   ![selection_001](https://cloud.githubusercontent.com/assets/3974108/12104563/d4f01512-b387-11e5-8b8d-9443e83abced.png) 
   
   本意应该是一个列表，但实际上却写成了“引用”。其他类似的格式问题还有不少。
2. 没有atom文件（http://marscfeng.github.io/atom.xml ），导致无法通过RSS订阅你的博客
3. 目前共有14篇博文，但在archives（http://marscfeng.github.io/archives/ ）里却只能看到10篇

**Comment by marscfeng** [comment]
哈哈，很惊喜……
冬哥，这个博客我暂时只是整理自己的笔记给自己看，才刚开始，没想到被你发现了。
既然冬哥提了问题，那我还是好好把问题解决一下。

多谢

From MarsCF's iPhone
